name: Basic deploy
on:
  push:
    branches:
      - release

jobs:
  EC2-Deploy:
    runs-on: ubuntu-latest
    steps:
      - id: deploy
        uses: bitovi/github-actions-deploy-docker-to-ec2@v1.0.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_default_region: us-east-1
          env_ghs: ${{ secrets.DOT_ENV }}

          aws_elb_app_port: 8080 # This should match the docker exposed port. Defaults to 3000.

          aws_r53_enable: true
          aws_r53_domain_name: armitage.xyz
          aws_r53_sub_domain_name: api
          aws_r53_create_sub_cert: true
          aws_elb_app_port: 8080
          aws_elb_listen_port: 443,8080
